import express from "express";
import { uploadDocument, getAllDocuments, getDocumentById, reviewDocument, deleteDocument } from "../controllers/documentController.js";
import authMiddleware from "../middleware/authMiddleware.js";
import roleMiddleware from "../middleware/roleMiddleware.js";
const router = express.Router();
router.use(authMiddleware);
router.post("/", uploadDocument);
router.get("/", getAllDocuments);
router.get("/:id", getDocumentById);
router.put("/:id/review", roleMiddleware(["admin", "tutor"]), reviewDocument);
router.delete("/:id", roleMiddleware(["admin"]), deleteDocument);
export default router;
